using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace EventApplication.Models
{
    public class SampleData : DropCreateDatabaseAlways<EventApplicationDB>
    //public class SampleData : DropCreateDatabaseIfModelChanges<EventApplicationDB>
    {
        protected override void Seed(EventApplicationDB context)
        {
            var eventTypes = new List<EventType>
            {
                new EventType{ Title = "Class" },
                new EventType{ Title = "Concert" },
                new EventType{ Title = "Conference" },
                new EventType{ Title = "Convention" },
                new EventType{ Title = "Expo" },
                new EventType{ Title = "Festival" },
                new EventType{ Title = "Party" },
                new EventType{ Title = "Race" },
                new EventType{ Title = "Rally" },
                new EventType{ Title = "Workshop" },
            };

            new List<Event>
            {
                new Event { EventType = eventTypes.Single(e => e.Title == "Class"), Title = "Example Class 1", Description = "This is a sample description for Example Class 1", StartDate = DateTime.Parse(DateTime.Today.AddDays(3).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(7).ToString()), City = "Austin", State = "Texas", OrganizerName = "Viola Todd", OrganizerContact = "123-456-7890", TicketsMax = 100, TicketsAvailable = 100 },
                new Event { EventType = eventTypes.Single(e => e.Title == "Class"), Title = "Example Class 2", Description = "This is a sample description for Example Class 2", StartDate = DateTime.Parse(DateTime.Today.AddDays(-9).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(-6).ToString()), City = "Tampa", State = "Florida", OrganizerName = "Spencer Collier", OrganizerContact = "123-456-7890", TicketsMax = 100, TicketsAvailable = 100 }, // Past event 1
                new Event { EventType = eventTypes.Single(e => e.Title == "Class"), Title = "Example Class 3", Description = "This is a sample description for Example Class 3", StartDate = DateTime.Parse(DateTime.Today.AddDays(1).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(8).ToString()), City = "Orlando", State = "Florida", OrganizerName = "Kristin Barton", OrganizerContact = "123-456-7890", TicketsMax = 100, TicketsAvailable = 100 }, // Last minute deal 1
                new Event { EventType = eventTypes.Single(e => e.Title == "Concert"), Title = "Example Concert 1", Description = "This is a sample description for Example Concert 1", StartDate = DateTime.Parse(DateTime.Today.AddDays(4).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(6).ToString()), City = "Parma", State = "Ohio", OrganizerName = "Brandon Ramirez", OrganizerContact = "123-456-7890", TicketsMax = 100, TicketsAvailable = 100 },
                new Event { EventType = eventTypes.Single(e => e.Title == "Concert"), Title = "Example Concert 2", Description = "This is a sample description for Example Concert 2", StartDate = DateTime.Parse(DateTime.Today.AddDays(-5).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(-3).ToString()), City = "Las Vegas", State = "Nevada", OrganizerName = "Sonya Jensen", OrganizerContact = "123-456-7890", TicketsMax = 100, TicketsAvailable = 100 }, // Past event 2
                new Event { EventType = eventTypes.Single(e => e.Title == "Concert"), Title = "Example Concert 3", Description = "This is a sample description for Example Concert 3", StartDate = DateTime.Parse(DateTime.Today.AddDays(1).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(8).ToString()), City = "Tampa", State = "Florida", OrganizerName = "Ed Richardson", OrganizerContact = "123-456-7890", TicketsMax = 100, TicketsAvailable = 100 }, // Last minute deal 2
                new Event { EventType = eventTypes.Single(e => e.Title == "Conference"), Title = "Example Conference 1", Description = "This is a sample description for Example Conference 1", StartDate = DateTime.Parse(DateTime.Today.AddDays(3).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(10).ToString()), City = "Orlando", State = "Florida", OrganizerName = "Susan Romero", OrganizerContact = "123-456-7890", TicketsMax = 100, TicketsAvailable = 100 },
                new Event { EventType = eventTypes.Single(e => e.Title == "Conference"), Title = "Example Conference 2", Description = "This is a sample description for Example Conference 2", StartDate = DateTime.Parse(DateTime.Today.AddDays(5).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(12).ToString()), City = "Laredo", State = "Texas", OrganizerName = "Willis Crawford", OrganizerContact = "123-456-7890", TicketsMax = 100, TicketsAvailable = 100 },
                new Event { EventType = eventTypes.Single(e => e.Title == "Conference"), Title = "Example Conference 3", Description = "This is a sample description for Example Conference 3", StartDate = DateTime.Parse(DateTime.Today.AddDays(1).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(8).ToString()), City = "Parma", State = "Ohio", OrganizerName = "Stacey Chambers", OrganizerContact = "123-456-7890", TicketsMax = 100, TicketsAvailable = 100 }, // Last minute deal 3
                new Event { EventType = eventTypes.Single(e => e.Title == "Convention"), Title = "Example Convention 1", Description = "This is a sample description for Example Convention 1", StartDate = DateTime.Parse(DateTime.Today.AddDays(3).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(19).ToString()), City = "Las Vegas", State = "Nevada", OrganizerName = "Loren Maxwell", OrganizerContact = "123-456-7890", TicketsMax = 100, TicketsAvailable = 100 },
                new Event { EventType = eventTypes.Single(e => e.Title == "Convention"), Title = "Example Convention 2", Description = "This is a sample description for Example Convention 2", StartDate = DateTime.Parse(DateTime.Today.AddDays(4).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(16).ToString()), City = "Columbus", State = "Ohio", OrganizerName = "Shirley Holt", OrganizerContact = "123-456-7890", TicketsMax = 100, TicketsAvailable = 100 },
                new Event { EventType = eventTypes.Single(e => e.Title == "Convention"), Title = "Example Convention 3", Description = "This is a sample description for Example Convention 3", StartDate = DateTime.Parse(DateTime.Today.AddDays(5).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(17).ToString()), City = "Laredo", State = "Texas", OrganizerName = "Abel Cortez", OrganizerContact = "123-456-7890", TicketsMax = 100, TicketsAvailable = 100 },
                new Event { EventType = eventTypes.Single(e => e.Title == "Expo"), Title = "Example Expo 1", Description = "This is a sample description for Example Expo 1", StartDate = DateTime.Parse(DateTime.Today.AddDays(8).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(14).ToString()), City = "Cincinnati", State = "Ohio", OrganizerName = "Moses Bridges", OrganizerContact = "123-456-7890", TicketsMax = 100, TicketsAvailable = 100 },
                new Event { EventType = eventTypes.Single(e => e.Title == "Expo"), Title = "Example Expo 2", Description = "This is a sample description for Example Expo 2", StartDate = DateTime.Parse(DateTime.Today.AddDays(4).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(8).ToString()), City = "Austin", State = "Texas", OrganizerName = "Sarah Rhea", OrganizerContact = "123-456-7890", TicketsMax = 100, TicketsAvailable = 100 },
                new Event { EventType = eventTypes.Single(e => e.Title == "Expo"), Title = "Example Expo 3", Description = "This is a sample description for Example Expo 3", StartDate = DateTime.Parse(DateTime.Today.AddDays(6).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(12).ToString()), City = "Parma", State = "Ohio", OrganizerName = "Brandon Ramirez", OrganizerContact = "123-456-7890", TicketsMax = 100, TicketsAvailable = 100 },
                new Event { EventType = eventTypes.Single(e => e.Title == "Festival"), Title = "Example Festival 1", Description = "This is a sample description for Example Festival 1", StartDate = DateTime.Parse(DateTime.Today.AddDays(-4).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(-3).ToString()), City = "Parma", State = "Ohio", OrganizerName = "Armando Baker", OrganizerContact = "123-456-7890", TicketsMax = 100, TicketsAvailable = 100 }, // Past event 3
                new Event { EventType = eventTypes.Single(e => e.Title == "Festival"), Title = "Example Festival 2", Description = "This is a sample description for Example Festival 2", StartDate = DateTime.Parse(DateTime.Today.AddDays(3).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(6).ToString()), City = "Cleveland", State = "Ohio", OrganizerName = "Alberto Sullivan", OrganizerContact = "123-456-7890", TicketsMax = 100, TicketsAvailable = 100 },
                new Event { EventType = eventTypes.Single(e => e.Title == "Festival"), Title = "Example Festival 3", Description = "This is a sample description for Example Festival 3", StartDate = DateTime.Parse(DateTime.Today.AddDays(8).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(12).ToString()), City = "Austin", State = "Texas", OrganizerName = "Jacquelyn Norman", OrganizerContact = "123-456-7890", TicketsMax = 100, TicketsAvailable = 100 },
                new Event { EventType = eventTypes.Single(e => e.Title == "Party"), Title = "Example Party 1", Description = "This is a sample description for Example Party 1", StartDate = DateTime.Parse(DateTime.Today.AddDays(3).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(15).ToString()), City = "Cleveland", State = "Ohio", OrganizerName = "Fredrick Peterson", OrganizerContact = "123-456-7890", TicketsMax = 100, TicketsAvailable = 100 },
                new Event { EventType = eventTypes.Single(e => e.Title == "Party"), Title = "Example Party 2", Description = "This is a sample description for Example Party 2", StartDate = DateTime.Parse(DateTime.Today.AddDays(1).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(12).ToString()), City = "Houston", State = "Texas", OrganizerName = "Andrew Murray", OrganizerContact = "123-456-7890", TicketsMax = 100, TicketsAvailable = 100 }, // Last minute deal 4
                new Event { EventType = eventTypes.Single(e => e.Title == "Party"), Title = "Example Party 3", Description = "This is a sample description for Example Party 3", StartDate = DateTime.Parse(DateTime.Today.AddDays(4).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(8).ToString()), City = "Laredo", State = "Texas", OrganizerName = "Julio Jacobs", OrganizerContact = "123-456-7890", TicketsMax = 100, TicketsAvailable = 100 },
                new Event { EventType = eventTypes.Single(e => e.Title == "Race"), Title = "Example Race 1", Description = "This is a sample description for Example Race 1", StartDate = DateTime.Parse(DateTime.Today.AddDays(4).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(8).ToString()), City = "Akron", State = "Ohio", OrganizerName = "Sandy Gibbs", OrganizerContact = "123-456-7890", TicketsMax = 100, TicketsAvailable = 100 },
                new Event { EventType = eventTypes.Single(e => e.Title == "Race"), Title = "Example Race 2", Description = "This is a sample description for Example Race 2", StartDate = DateTime.Parse(DateTime.Today.AddDays(-5).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(-3).ToString()), City = "Parma", State = "Ohio", OrganizerName = "Shirly Curry", OrganizerContact = "123-456-7890", TicketsMax = 100, TicketsAvailable = 100 }, // Past event 4
                new Event { EventType = eventTypes.Single(e => e.Title == "Race"), Title = "Example Race 3", Description = "This is a sample description for Example Race 3", StartDate = DateTime.Parse(DateTime.Today.AddDays(3).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(18).ToString()), City = "Tampa", State = "Florida", OrganizerName = "Marvin Maldonado", OrganizerContact = "123-456-7890", TicketsMax = 100, TicketsAvailable = 100 },
                new Event { EventType = eventTypes.Single(e => e.Title == "Rally"), Title = "Example Rally 1", Description = "This is a sample description for Example Rally 1", StartDate = DateTime.Parse(DateTime.Today.AddDays(3).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(16).ToString()), City = "Akron", State = "Ohio", OrganizerName = "Abraham Cox", OrganizerContact = "123-456-7890", TicketsMax = 100, TicketsAvailable = 100 },
                new Event { EventType = eventTypes.Single(e => e.Title == "Rally"), Title = "Example Rally 2", Description = "This is a sample description for Example Rally 2", StartDate = DateTime.Parse(DateTime.Today.AddDays(6).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(13).ToString()), City = "Las Vegas", State = "Nevada", OrganizerName = "Dennis Carlson", OrganizerContact = "123-456-7890", TicketsMax = 100, TicketsAvailable = 100 },
                new Event { EventType = eventTypes.Single(e => e.Title == "Rally"), Title = "Example Rally 3", Description = "This is a sample description for Example Rally 3", StartDate = DateTime.Parse(DateTime.Today.AddDays(-8).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(-1).ToString()), City = "Cincinnati", State = "Ohio", OrganizerName = "Debbie Snyder", OrganizerContact = "123-456-7890", TicketsMax = 100, TicketsAvailable = 100 }, // Past event 5
                new Event { EventType = eventTypes.Single(e => e.Title == "Workshop"), Title = "Example Workshop 1", Description = "This is a sample description for Example Workshop 1", StartDate = DateTime.Parse(DateTime.Today.AddDays(4).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(16).ToString()), City = "Parma", State = "Ohio", OrganizerName = "Cindy Roberts", OrganizerContact = "123-456-7890", TicketsMax = 100, TicketsAvailable = 100 },
                new Event { EventType = eventTypes.Single(e => e.Title == "Workshop"), Title = "Example Workshop 2", Description = "This is a sample description for Example Workshop 2", StartDate = DateTime.Parse(DateTime.Today.AddDays(1).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(5).ToString()), City = "Columbus", State = "Ohio", OrganizerName = "Shawn Harrison", OrganizerContact = "123-456-7890", TicketsMax = 100, TicketsAvailable = 100 }, // Last minute deal 5
                new Event { EventType = eventTypes.Single(e => e.Title == "Workshop"), Title = "Example Workshop 3", Description = "This is a sample description for Example Workshop 3", StartDate = DateTime.Parse(DateTime.Today.AddDays(7).ToString()), EndDate = DateTime.Parse(DateTime.Today.AddDays(15).ToString()), City = "Cincinnati", State = "Ohio", OrganizerName = "Elias Grant", OrganizerContact = "123-456-7890", TicketsMax = 100, TicketsAvailable = 100 },
            }.ForEach(e => context.Events.Add(e));

            context.Configuration.ValidateOnSaveEnabled = false;
            context.SaveChanges();
        }
    }
}